import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: uuid(),
    firstName: "Chris",
    lastName: "Gayle",
    email: "chrisgayle@gmail.com",
    username: "chrisgayle@gmail.com",
    bio: "I am a Potato.",
    password: "chris123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    portfolio: "https://www.google.com/",
    avatarURL: "https://res.cloudinary.com/dnkpd7qq8/image/upload/v1654708826/social/gayle_objvho.jpg",
    following: [],
    followers: [],
    bookmarks: [],
  },
  {
    _id: uuid(),
    firstName: "Yuvraj",
    lastName: "Singh",
    email: "yuvrajsingh@gmail.com",
    username: "yuvrajsingh@gmail.com",
    bio: "I am a Racer.",
    password: "yuvraj123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    portfolio: "https://www.google.com/",
    avatarURL: "https://res.cloudinary.com/dnkpd7qq8/image/upload/v1654708831/social/Yuvraj_u50uxv.webp",
    following: [],
    followers: [],
    bookmarks: [],
  },
  {
    _id: uuid(),
    firstName: "Heath",
    lastName: "Ledger",
    email: "heathledger@gmail.com",
    username: "heathledger@gmail.com",
    bio: "Madness is a lot like gravity.",
    password: "heath123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    portfolio: "https://www.google.com/",
    avatarURL: "https://res.cloudinary.com/dnkpd7qq8/image/upload/v1654708031/social/joker_nvldlf.jpg",
    following: [],
    followers: [],
    bookmarks: [],
  },
  {
    _id: uuid(),
    firstName: "Christian",
    lastName: "Bale",
    email: "christianbale@gmail.com",
    username: "christianbale@gmail.com",
    bio: "I am Batman.",
    password: "chistian123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    portfolio: "https://www.google.com/",
    avatarURL:
      "https://res.cloudinary.com/dnkpd7qq8/image/upload/v1654707117/social/batman_uxhska.webp",
    following: [],
    followers: [],
    bookmarks: [],
  },
  {
    _id: uuid(),
    firstName: "Peter",
    lastName: "Parker",
    email: "peterparker@gmail.com",
    username: "peterparker@gmail.com",
    bio: "With great power comes great responsibility.",
    password: "peter123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    portfolio: "https://www.google.com/",
    avatarURL:
      "https://res.cloudinary.com/dnkpd7qq8/image/upload/v1654707119/social/format-arw-PXjQaGxi4JA-unsplash_kzepik.jpg",
    following: [],
    followers: [],
    bookmarks: [],
  },
  {
    _id: uuid(),
    firstName: "Clark",
    lastName: "Kent",
    email: "clarkkent@gmail.com",
    username: "clarkkent@gmail.com",
    bio: "Do good to others and every man can be a Superman.",
    password: "clark123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    portfolio: "https://www.google.com/",
    avatarURL: "https://res.cloudinary.com/dnkpd7qq8/image/upload/v1654708537/social/superman_pk0hkl.jpg",
    following: [],
    followers: [],
    bookmarks: [],
  },
  {
    _id: uuid(),
    firstName: "Steve",
    lastName: "Rogers",
    email: "steverogers@gmail.com",
    username: "steverogers@gmail.com",
    bio: "I'm just a kid from Brooklyn.",
    password: "steve123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    portfolio: "https://www.google.com/",
    avatarURL: "https://res.cloudinary.com/dnkpd7qq8/image/upload/v1654708287/social/captain_iq3qpc.webp",
    following: [],
    followers: [],
    bookmarks: [],
  },
  {
    _id: uuid(),
    firstName: "Tony",
    lastName: "Stark",
    email: "tonystark@gmail.com",
    username: "tonystark@gmail.com",
    bio: "Sometimes you've gotta run before you can walk.",
    password: "stark123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    portfolio: "https://www.google.com/",
    avatarURL: "https://res.cloudinary.com/dnkpd7qq8/image/upload/v1654708159/social/ironman_s6bisj.jpg",
    following: [],
    followers: [],
    bookmarks: [],
  },
];
